In [1]:
#importing numpy
import numpy as np

#creating arrays
arr= np.array([1,2,3,4,5])
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
#shape
print(arr.shape)

(5,)


In [12]:
arr= np.array([1,2,3,4,5,6])
arr1=arr.reshape(2,3)
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [22]:
#arange,ones,eye
#arange
arr2=np.arange(0,10,2)#[0,2,4,6,8]
print(arr2)
arr_reshaped=arr2.reshape(5,1)
print(arr_reshaped)

#ones
arr3=np.ones((3,3))
print(arr3)

arr4=np.zeros((2,2,))
print(arr4)

#eye
arr5=np.eye(3)
print(arr5)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#shape,ndim,size,dtype,itemsize
arr=np.array([1,2,3,4,5])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(5,)
1
5
int64
8


In [24]:
#Vectorized operation
arr1=np.array([2,3,4,5])
arr2=np.array([4,3,4,6])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 6  6  8 11]
[-2  0  0 -1]
[ 8  9 16 30]
[0.5        1.         1.         0.83333333]


In [25]:
#universal functions->sqrt,exp,sin and log
arr1=np.array([2,3,4,5])
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))


[1.41421356 1.73205081 2.         2.23606798]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [42]:
arr1=np.array([[2,3,4,5],[3,4,5,6],[4,5,6,7]])
print(arr1)

print("\n",arr1[1:])
print("\n",arr1[0, 0])
print("\n",arr1[1:][1:3])


[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]

 [[3 4 5 6]
 [4 5 6 7]]

 2

 [[4 5 6 7]]


In [43]:
#modifying array
arr1[0,0]=100
print(arr1)
arr1[1:]=100
print(arr1)

[[100   3   4   5]
 [  3   4   5   6]
 [  4   5   6   7]]
[[100   3   4   5]
 [100 100 100 100]
 [100 100 100 100]]


In [45]:
#Statistical Operations and Normalization
data=[1,2,3,4,5,6,7,8]
mean=np.mean(data)

median=np.median(data)
std=np.std(data)
var=np.var(data)
print(np.mean(data))
print(median)
print(std)
print(var)

4.5
4.5
2.29128784747792
5.25
