In [5]:
import numpy as np

#creating array from list
arr1=[1,2,3,45]
print(arr1)


#creating array from the numpy
arr=np.array([1,2,3,3])
print(arr)

#creating 2darray from the numpy
arr=np.array([[1,2,3,3],[4,5,6,7]])
print(arr)

[1, 2, 3, 45]
[1 2 3 3]
[[1 2 3 3]
 [4 5 6 7]]


In [ ]:
#multiplying by 2
#list
arr1=arr1*2
print(arr1)#increase each element make double size

arr=arr*2
print(arr)#multiplying each element by 2

[1, 2, 3, 45, 1, 2, 3, 45]
[[ 2  4  6  6]
 [ 8 10 12 14]]


In [8]:
import time
start=time.time()
py_list=[i**2 for i in range(5)]
time.sleep(1.23456)
print(time.time()-start)

1.2353971004486084


In [15]:
zeroMatrix=np.zeros((2,3))
print(zeroMatrix)

oneMatrix=np.ones((2,3))
print(oneMatrix)

#identity matrix 
identiy=np.eye(3)
print(identiy)

specific=np.full((2,3),7)
print(specific)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7 7]
 [7 7 7]]


In [22]:
#random
random=np.random.random((2,3))
print(random)

sequence=np.arange(0,11,2)
print(sequence)
print(sequence.reshape(2,3))

[[0.09615379 0.05047649 0.33281041]
 [0.12746014 0.38154236 0.7258221 ]]
[ 0  2  4  6  8 10]
[[ 0  2  4]
 [ 6  8 10]]


In [24]:
#Tensor in python is array with morethan 2d

tensor=np.array(
    [
        [
            [1,2,3],[3,2,1]
        ],
        [
            [6,7,8],[8,7,6]
        ]
    ])
print(tensor)

[[[1 2 3]
  [3 2 1]]

 [[6 7 8]
  [8 7 6]]]


In [31]:
#Array properties
arr=np.array([[1,2,3],[3,4,5]]
            )
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)
flattened=arr.flatten()
print(flattened)
ravel=arr.ravel()
print(ravel)
Transpose=flattened.T
print(Transpose)


2
int64
(2, 3)
6
[1 2 3 3 4 5]
[1 2 3 3 4 5]
[1 2 3 3 4 5]
