In [5]:
#Indexing and slicin
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print("Basic Slicing:",arr[2:7])
print("With step",arr[2:7:2])


Basic Slicing: [3 4 5 6 7]
With step [3 5 7]


In [10]:
#slicing with 2d array
arr_2d=np.array([[1,2,3],[2,3,4],[4,5,6]])
print("specific element",arr_2d[2][1])
print ("whole row",arr_2d[1])
print("whole column",arr_2d[:,1])

specific element 5
whole row [2 3 4]
whole column [2 3 5]


In [11]:
arr=np.array([1,2,5,3,33,4,5,6,7])
print("sorted array",np.sort(arr))

sorted array [ 1  2  3  4  5  5  6  7 33]


In [14]:
arr_2d=np.array([[6,2,3],[2,3,4],[4,5,6]])
print("sorted by column:",np.sort(arr_2d,axis=0))
print("sorted by row",np.sort(arr_2d,axis=1))

sorted by column: [[2 2 3]
 [4 3 4]
 [6 5 6]]
sorted by row [[2 3 6]
 [2 3 4]
 [4 5 6]]


In [22]:
#Filter
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

index = [numbers%2==0]
numbers = numbers[numbers%2==0]
print(numbers)
print(index)

[ 2  4  6  8 10]
[array([False,  True, False,  True, False,  True, False,  True, False,
        True])]


In [23]:
#filter with mask
mask=numbers%2==0
numbers = numbers[mask]
print(numbers)

[ 2  4  6  8 10]


In [37]:
#fancy indexing
index=[0,2,4]
print(numbers[index])

#Np.where
numbers = np.array([1,2,3,4,5,6,7,88,8,9,10])
where_result=np.where(numbers>5)
print(where_result)
print("np where ",numbers[where_result])

[1 3 5]
(array([ 5,  6,  7,  8,  9, 10]),)
np where  [ 6  7 88  8  9 10]


In [35]:
#where
condition = np.where(numbers>5,numbers*2,"false")
print(condition)

['false' 'false' 'false' 'false' 'false' '12' '14' '16' '18' '20']


In [40]:
#adding and removing data 
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
arr=np.array([1,2,3,4,5,6,7])
combined=np.concatenate((numbers,arr))
print(combined)

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7]
