In [229]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


In [230]:
from sklearn.datasets import load_iris

In [231]:
from sklearn.model_selection import train_test_split

In [232]:
x,y=load_iris(return_X_y=True)

In [233]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [234]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [235]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=10)

In [236]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

In [237]:
gnb.fit(xtrain,ytrain)

GaussianNB()

In [238]:
y_pred=gnb.predict(xtest)

In [239]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_pred,ytest))
print(accuracy_score(y_pred,ytest))
print(classification_report(y_pred,ytest))

[[11  0  0]
 [ 0 15  0]
 [ 0  0 12]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [240]:
df=sns.load_dataset('tips')
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [241]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [242]:
df.describe()

,total_bill,tip,size
count,244.000000,244.000000,244.000000
mean,19.785943,2.998279,2.569672
std,8.902412,1.383638,0.951100
min,3.070000,1.000000,1.000000
25%,13.347500,2.000000,2.000000
50%,17.795000,2.900000,2.000000
75%,24.127500,3.562500,3.000000
max,50.810000,10.000000,6.000000


In [243]:
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [244]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [245]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])

In [246]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,0,No,Sun,Dinner,2
1,10.34,1.66,1,No,Sun,Dinner,3
2,21.01,3.50,1,No,Sun,Dinner,3
3,23.68,3.31,1,No,Sun,Dinner,2
4,24.59,3.61,0,No,Sun,Dinner,4


In [247]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [248]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['time']=le.fit_transform(df['time'])

In [249]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [250]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['smoker']=le.fit_transform(df['sex'])

In [251]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [252]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
array=one.fit_transform(df[['day']]).toarray()
df2=pd.DataFrame(data=array,columns=one.get_feature_names_out())
df2.head()

,day_Fri,day_Sat,day_Sun,day_Thur
0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0


In [253]:
df=pd.concat([df,df2],axis=1)
df.drop(columns='day',axis=-1,inplace=True)

In [254]:
df.head()

,total_bill,tip,sex,smoker,time,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,0,0,0,2,0.0,0.0,1.0,0.0
1,10.34,1.66,1,1,0,3,0.0,0.0,1.0,0.0
2,21.01,3.50,1,1,0,3,0.0,0.0,1.0,0.0
3,23.68,3.31,1,1,0,2,0.0,0.0,1.0,0.0
4,24.59,3.61,0,0,0,4,0.0,0.0,1.0,0.0


In [255]:
#independent and dependent
y=df['time']
x=df.drop(columns='time',axis=-1)


In [256]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: time, Length: 244, dtype: int64

In [257]:
x

,total_bill,tip,sex,smoker,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,0,0,2,0.0,0.0,1.0,0.0
1,10.34,1.66,1,1,3,0.0,0.0,1.0,0.0
2,21.01,3.50,1,1,3,0.0,0.0,1.0,0.0
3,23.68,3.31,1,1,2,0.0,0.0,1.0,0.0
4,24.59,3.61,0,0,4,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,1,1,3,0.0,1.0,0.0,0.0
240,27.18,2.00,0,0,2,0.0,1.0,0.0,0.0
241,22.67,2.00,1,1,2,0.0,1.0,0.0,0.0
242,17.82,1.75,1,1,2,0.0,1.0,0.0,0.0


In [258]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=42)

In [260]:
from sklearn.naive_bayes import BernoulliNB
brn=BernoulliNB()
brn.fit(xtrain,ytrain)

BernoulliNB()

In [261]:
y_pred=brn.predict(xtest)

In [262]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_pred,ytest))
print(accuracy_score(y_pred,ytest))
print(classification_report(y_pred,ytest))

[[43  0]
 [ 1 17]]
0.9836065573770492
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        43
           1       1.00      0.94      0.97        18

    accuracy                           0.98        61
   macro avg       0.99      0.97      0.98        61
weighted avg       0.98      0.98      0.98        61

